### ISSUE TITLE
error in launch

### ISSUE THREAD

**Issue by behnammodi** [joscha/storybook-addon-i18n-tools#5]
<img width="591" alt="screen shot 2019-01-22 at 11 13 32 am" src="https://user-images.githubusercontent.com/1549069/51519646-d0b37580-1e36-11e9-9c36-3c6325414935.png">

**Comment by wmurray-es** [comment]
Seems like there is (still) a missing dependency.

`npm i @kadira/storybook-addons --save-dev` solved this
